import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import GoogleAdsense from "./GoogleAdsense";
import Providers from "./Providers";
import Header from "./Header";
import Footer from "./Footer";

export const runtime = "edge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <GoogleAdsense pId="4436108648632802" />
      </head>
      <body className={`${inter.className} dark`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
      <GoogleAnalytics gaId="G-1GELWPGE7D" />
    </html>
  );
}
